name: Release

on:
   push:

env:
  DOCKER_BUILDKIT: '1'
  FORCE_COLOR: 1

jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Generate Package
        run: |
          pip3 install build
          python -m build .
        env:
          # This is also supported by Hatch; see
          # https://github.com/ofek/hatch-vcs#version-source-environment-variables
          SETUPTOOLS_SCM_PRETEND_VERSION: 1.0.0
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

